/**
 * Musculatura de la cintura escapular, el hombro y el brazo, por porciones.
 *
 * Ojo con los ejes: húmero y antebrazo llevan un reposo de 180° en X, así que
 * en ESOS huesos el +Z local apunta hacia ATRÁS del cuerpo.
 */

import type { Musculo } from './anatomia'

export const MUSCULOS_SUPERIOR: Musculo[] = [
  // ======================= CINTURA ESCAPULAR ==============================
  {
    id: 'trapecio',
    nombre: 'Trapecio',
    grupo: 'escapula',
    acciones: [
      'Sus tres porciones tiran en direcciones distintas: la alta sube el hombro, la media lo junta y la baja lo baja.',
      'Rota la escápula hacia arriba, que es lo que deja pasar el brazo por encima de la cabeza.',
    ],
    porciones: [
      {
        id: 'superior',
        nombre: 'Porción descendente',
        origen: 'Occipital y ligamento nucal',
        insercion: 'Tercio lateral de la clavícula',
        desde: ['cuello', 0.55, [0.006, 0, -0.026]],
        hasta: ['clavicula', 0.82, [0.002, 0, -0.014]],
        radio: 0.016, aplanar: 0.5,
      },
      {
        id: 'medio',
        nombre: 'Porción transversa',
        origen: 'Apófisis espinosas de C7 a T3',
        insercion: 'Acromion y espina de la escápula',
        desde: ['torax', 0.80, [0.010, 0, -0.034]],
        hasta: ['escapula', 0.42, [-0.024, 0, -0.016]],
        radio: 0.017, aplanar: 0.4,
      },
      {
        id: 'inferior',
        nombre: 'Porción ascendente',
        origen: 'Apófisis espinosas de T4 a T12',
        insercion: 'Extremo medial de la espina de la escápula',
        desde: ['torax', 0.34, [0.010, 0, -0.036]],
        hasta: ['escapula', 0.16, [-0.010, 0, -0.014]],
        radio: 0.015, aplanar: 0.4,
      },
    ],
  },
  {
    id: 'romboides',
    nombre: 'Romboides',
    grupo: 'escapula',
    acciones: [
      'Juntan la escápula hacia la columna y la rotan hacia abajo.',
      'Son los que se aprietan al final de un remo.',
    ],
    porciones: [
      {
        id: 'menor',
        nombre: 'Romboides menor',
        origen: 'Apófisis espinosas de C7 y T1',
        insercion: 'Borde medial de la escápula, a la altura de la espina',
        desde: ['torax', 0.82, [0.010, 0, -0.030]],
        hasta: ['escapula', 0.60, [0.004, 0, -0.012]],
        radio: 0.012, aplanar: 0.42,
      },
      {
        id: 'mayor',
        nombre: 'Romboides mayor',
        origen: 'Apófisis espinosas de T2 a T5',
        insercion: 'Borde medial de la escápula, por debajo de la espina',
        desde: ['torax', 0.66, [0.010, 0, -0.032]],
        hasta: ['escapula', 0.34, [0.004, 0, -0.012]],
        radio: 0.014, aplanar: 0.42,
      },
    ],
  },
  {
    id: 'serrato',
    nombre: 'Serrato anterior',
    grupo: 'escapula',
    acciones: [
      'Pega la escápula a las costillas y la lleva hacia delante.',
      'Si no entra, la escápula se despega y el hombro pierde su base al empujar.',
    ],
    porciones: [
      {
        id: 'unico',
        nombre: 'Digitaciones costales',
        origen: 'Caras laterales de las costillas 1.ª a 9.ª',
        insercion: 'Borde medial de la escápula, por su cara anterior',
        desde: ['torax', 0.36, [0.088, 0, 0.030]],
        hasta: ['escapula', 0.55, [0.012, 0, 0.002]],
        radio: 0.011, aplanar: 0.55, fasciculos: 3,
        abanicoDesde: [0.008, 0.090, -0.014],
        abanicoHasta: [0.002, -0.100, 0],
      },
    ],
  },
  {
    id: 'pectoral_menor',
    nombre: 'Pectoral menor',
    grupo: 'escapula',
    acciones: ['Tira de la escápula hacia delante y abajo; acortado, cierra el hombro.'],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre único',
        origen: 'Costillas 3.ª a 5.ª',
        insercion: 'Apófisis coracoides de la escápula',
        desde: ['torax', 0.34, [0.052, 0, 0.062]],
        hasta: ['escapula', 0.80, [0.030, 0, 0.014]],
        radio: 0.011, aplanar: 0.55,
      },
    ],
  },

  // ============================= HOMBRO ===================================
  {
    id: 'deltoides',
    nombre: 'Deltoides',
    grupo: 'hombro',
    acciones: [
      'Tres porciones y tres direcciones: la anterior lleva el brazo adelante, la media al lado y la posterior atrás.',
      'Solo trabajan juntas al frenar; en cada ejercicio manda una.',
    ],
    porciones: [
      {
        id: 'anterior',
        nombre: 'Porción clavicular',
        origen: 'Tercio lateral de la clavícula',
        insercion: 'Tuberosidad deltoidea del húmero',
        desde: ['clavicula', 0.80, [0.004, 0, 0.016]],
        hasta: ['brazo', 0.44, [0.016, 0, -0.010]],
        via: [['brazo', 0.12, [0.030, 0, -0.022]]],
        radio: 0.016, aplanar: 0.62,
      },
      {
        id: 'medio',
        nombre: 'Porción acromial',
        origen: 'Acromion',
        insercion: 'Tuberosidad deltoidea del húmero',
        desde: ['escapula', 0.86, [0.018, 0, -0.008]],
        hasta: ['brazo', 0.46, [0.026, 0, 0]],
        via: [['brazo', 0.14, [0.040, 0, 0]]],
        radio: 0.018, aplanar: 0.66,
      },
      {
        id: 'posterior',
        nombre: 'Porción espinal',
        origen: 'Espina de la escápula',
        insercion: 'Tuberosidad deltoidea del húmero',
        desde: ['escapula', 0.58, [0.010, 0, -0.022]],
        hasta: ['brazo', 0.44, [0.014, 0, 0.014]],
        via: [['brazo', 0.13, [0.030, 0, 0.026]]],
        radio: 0.015, aplanar: 0.6,
      },
    ],
  },
  {
    id: 'manguito',
    nombre: 'Manguito rotador',
    grupo: 'hombro',
    acciones: [
      'Sujeta la cabeza del húmero en su sitio mientras el hombro se mueve.',
      'No mueve peso: centra la articulación para que el deltoides pueda tirar.',
    ],
    porciones: [
      {
        id: 'supraespinoso',
        nombre: 'Supraespinoso',
        origen: 'Fosa supraespinosa de la escápula',
        insercion: 'Faceta superior del troquíter',
        desde: ['escapula', 0.56, [-0.004, 0, -0.020]],
        hasta: ['brazo', 0.04, [0.024, 0, -0.002]],
        via: [['escapula', 0.84, [0.014, 0, -0.012]]],
        radio: 0.010, aplanar: 0.5,
      },
      {
        id: 'infraespinoso',
        nombre: 'Infraespinoso',
        origen: 'Fosa infraespinosa de la escápula',
        insercion: 'Faceta media del troquíter',
        desde: ['escapula', 0.38, [0.020, 0, -0.014]],
        hasta: ['brazo', 0.07, [0.022, 0, 0.010]],
        radio: 0.012, aplanar: 0.45,
      },
      {
        id: 'redondo_menor',
        nombre: 'Redondo menor',
        origen: 'Borde lateral de la escápula',
        insercion: 'Faceta inferior del troquíter',
        desde: ['escapula', 0.24, [0.018, 0, -0.010]],
        hasta: ['brazo', 0.09, [0.020, 0, 0.012]],
        radio: 0.009, aplanar: 0.6,
      },
      {
        id: 'subescapular',
        nombre: 'Subescapular',
        origen: 'Fosa subescapular, en la cara anterior de la escápula',
        insercion: 'Troquín, el tubérculo menor del húmero',
        desde: ['escapula', 0.40, [0.016, 0, 0.010]],
        hasta: ['brazo', 0.06, [0.012, 0, -0.016]],
        radio: 0.011, aplanar: 0.5,
      },
    ],
  },
  {
    id: 'redondo_mayor',
    nombre: 'Redondo mayor',
    grupo: 'hombro',
    acciones: ['Baja y rota el brazo hacia dentro; acompaña al dorsal en cada tracción.'],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre único',
        origen: 'Ángulo inferior de la escápula',
        insercion: 'Cresta del tubérculo menor del húmero',
        desde: ['escapula', 0.12, [0.016, 0, -0.006]],
        hasta: ['brazo', 0.15, [0.006, 0, 0.018]],
        radio: 0.013, aplanar: 0.6,
      },
    ],
  },
  {
    id: 'dorsal_ancho',
    nombre: 'Dorsal ancho',
    grupo: 'hombro',
    acciones: [
      'Baja el brazo desde arriba y lo lleva hacia atrás: es el motor de toda tracción.',
      'Nace en la pelvis y acaba en el húmero, así que también sujeta la columna.',
    ],
    porciones: [
      {
        id: 'vertebral',
        nombre: 'Fibras vertebrales',
        origen: 'Apófisis espinosas de T7 a L5, por la fascia toracolumbar',
        insercion: 'Surco intertubercular del húmero',
        desde: ['torax', 0.30, [0.020, 0, -0.040]],
        hasta: ['brazo', 0.14, [0.008, 0, 0.018]],
        via: [['torax', 0.42, [0.090, 0, -0.014]]],
        radio: 0.021, aplanar: 0.4, fasciculos: 2,
        abanicoDesde: [0.004, 0.170, 0.004],
      },
      {
        id: 'iliaca',
        nombre: 'Fibras ilíacas',
        origen: 'Tercio posterior de la cresta ilíaca',
        insercion: 'Surco intertubercular del húmero',
        desde: ['pelvis', 0, [0.048, 0.062, -0.044]],
        hasta: ['brazo', 0.15, [0.010, 0, 0.020]],
        via: [['torax', 0.28, [0.096, 0, -0.006]]],
        radio: 0.020, aplanar: 0.4, fasciculos: 2,
        abanicoDesde: [0.018, 0.026, 0.010],
      },
      {
        id: 'costal',
        nombre: 'Fibras costales',
        origen: 'Costillas 9.ª a 12.ª',
        insercion: 'Surco intertubercular del húmero',
        desde: ['torax', 0.16, [0.070, 0, 0.010]],
        hasta: ['brazo', 0.13, [0.010, 0, 0.016]],
        via: [['torax', 0.40, [0.098, 0, -0.002]]],
        radio: 0.016, aplanar: 0.42,
      },
    ],
  },
  {
    id: 'pectoral_mayor',
    nombre: 'Pectoral mayor',
    grupo: 'hombro',
    acciones: [
      'Cruza el brazo hacia delante y hacia dentro.',
      'La porción clavicular tira hacia arriba y la esternal hacia abajo: por eso el ángulo del banco cambia lo que trabaja.',
    ],
    porciones: [
      {
        id: 'clavicular',
        nombre: 'Porción clavicular',
        origen: 'Mitad medial de la clavícula',
        insercion: 'Cresta del tubérculo mayor del húmero',
        desde: ['clavicula', 0.42, [0.002, 0, 0.014]],
        hasta: ['brazo', 0.12, [0.010, 0, -0.022]],
        radio: 0.015, aplanar: 0.48, fasciculos: 2,
        abanicoDesde: [0.004, 0.070, -0.002],
      },
      {
        id: 'esternocostal',
        nombre: 'Porción esternocostal',
        origen: 'Esternón y cartílagos costales 1.º a 6.º',
        insercion: 'Cresta del tubérculo mayor del húmero',
        desde: ['torax', 0.34, [0.018, 0, 0.080]],
        hasta: ['brazo', 0.15, [0.008, 0, -0.020]],
        radio: 0.020, aplanar: 0.45, fasciculos: 3,
        abanicoDesde: [0.006, 0.120, -0.008],
      },
      {
        id: 'abdominal',
        nombre: 'Porción abdominal',
        origen: 'Aponeurosis del oblicuo externo',
        insercion: 'Cresta del tubérculo mayor, en la parte más alta de la inserción',
        desde: ['torax', 0.10, [0.026, 0, 0.070]],
        hasta: ['brazo', 0.17, [0.008, 0, -0.018]],
        radio: 0.014, aplanar: 0.45,
      },
    ],
  },
  {
    id: 'coracobraquial',
    nombre: 'Coracobraquial',
    grupo: 'hombro',
    acciones: ['Lleva el brazo adelante y hacia la línea media.'],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre único',
        origen: 'Apófisis coracoides de la escápula',
        insercion: 'Cara medial del húmero, en su tercio medio',
        desde: ['escapula', 0.78, [0.008, 0, 0.010]],
        hasta: ['brazo', 0.45, [-0.014, 0, -0.006]],
        radio: 0.010, aplanar: 0.75,
      },
    ],
  },

  // ============================== CODO ====================================
  {
    id: 'biceps',
    nombre: 'Bíceps braquial',
    grupo: 'codo',
    acciones: [
      'Flexiona el codo y gira la palma hacia arriba.',
      'Sus dos cabezas nacen en la escápula, así que también participa en el hombro.',
    ],
    porciones: [
      {
        id: 'larga',
        nombre: 'Cabeza larga',
        origen: 'Tubérculo supraglenoideo de la escápula',
        insercion: 'Tuberosidad del radio',
        desde: ['escapula', 0.76, [0.012, 0, 0.004]],
        hasta: ['antebrazo', 0.16, [0.012, 0, -0.014]],
        via: [['brazo', 0.06, [0.014, 0, -0.014]], ['brazo', 0.52, [0.012, 0, -0.026]]],
        radio: 0.014, aplanar: 0.85, biarticular: true,
      },
      {
        id: 'corta',
        nombre: 'Cabeza corta',
        origen: 'Apófisis coracoides de la escápula',
        insercion: 'Tuberosidad del radio, con la cabeza larga',
        desde: ['escapula', 0.78, [0.002, 0, 0.012]],
        hasta: ['antebrazo', 0.15, [0.008, 0, -0.014]],
        via: [['brazo', 0.50, [-0.004, 0, -0.026]]],
        radio: 0.013, aplanar: 0.85, biarticular: true,
      },
    ],
  },
  {
    id: 'braquial',
    nombre: 'Braquial',
    grupo: 'codo',
    acciones: [
      'Flexiona el codo y solo eso: no gira la palma ni cruza el hombro.',
      'Es el que más trabaja con la palma mirando hacia dentro.',
    ],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre único',
        origen: 'Mitad distal de la cara anterior del húmero',
        insercion: 'Tuberosidad del cúbito',
        desde: ['brazo', 0.50, [0.004, 0, -0.020]],
        hasta: ['antebrazo', 0.11, [-0.008, 0, -0.013]],
        radio: 0.012, aplanar: 0.8,
      },
    ],
  },
  {
    id: 'braquiorradial',
    nombre: 'Braquiorradial',
    grupo: 'codo',
    acciones: ['Flexiona el codo con la palma de canto; es el vientre del antebrazo que se marca.'],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre único',
        origen: 'Cresta supracondílea lateral del húmero',
        insercion: 'Apófisis estiloides del radio',
        desde: ['brazo', 0.84, [0.020, 0, -0.012]],
        hasta: ['antebrazo', 0.86, [0.014, 0, -0.008]],
        via: [['antebrazo', 0.30, [0.024, 0, -0.016]]],
        radio: 0.012, aplanar: 0.7,
      },
    ],
  },
  {
    id: 'triceps',
    nombre: 'Tríceps braquial',
    grupo: 'codo',
    acciones: [
      'Extiende el codo: es dos tercios del volumen del brazo.',
      'Solo la cabeza larga cruza el hombro, y por eso solo ella se estira al levantar el brazo.',
    ],
    porciones: [
      {
        id: 'larga',
        nombre: 'Cabeza larga',
        origen: 'Tubérculo infraglenoideo de la escápula',
        insercion: 'Olécranon del cúbito',
        desde: ['escapula', 0.14, [0.010, 0, -0.010]],
        hasta: ['antebrazo', 0.03, [0, 0, 0.022]],
        via: [['brazo', 0.55, [0.002, 0, 0.028]]],
        radio: 0.016, aplanar: 0.82, biarticular: true,
      },
      {
        id: 'lateral',
        nombre: 'Cabeza lateral',
        origen: 'Cara posterior del húmero, por encima del surco radial',
        insercion: 'Olécranon del cúbito',
        desde: ['brazo', 0.22, [0.022, 0, 0.020]],
        hasta: ['antebrazo', 0.03, [0.006, 0, 0.022]],
        via: [['brazo', 0.62, [0.018, 0, 0.026]]],
        radio: 0.014, aplanar: 0.8,
      },
      {
        id: 'medial',
        nombre: 'Cabeza medial',
        origen: 'Cara posterior del húmero, por debajo del surco radial',
        insercion: 'Olécranon del cúbito',
        desde: ['brazo', 0.42, [-0.016, 0, 0.020]],
        hasta: ['antebrazo', 0.03, [-0.006, 0, 0.020]],
        via: [['brazo', 0.72, [-0.012, 0, 0.024]]],
        radio: 0.012, aplanar: 0.8,
      },
    ],
  },
  {
    id: 'pronador_redondo',
    nombre: 'Pronador redondo',
    grupo: 'codo',
    acciones: ['Gira la palma hacia abajo.'],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre único',
        origen: 'Epicóndilo medial del húmero y apófisis coronoides',
        insercion: 'Cara lateral del radio, en su tercio medio',
        desde: ['brazo', 0.94, [-0.016, 0, -0.010]],
        hasta: ['antebrazo', 0.42, [0.016, 0, -0.006]],
        radio: 0.010, aplanar: 0.7,
      },
    ],
  },
  {
    id: 'flexores_carpo',
    nombre: 'Flexores del carpo',
    grupo: 'codo',
    acciones: [
      'Cierran la muñeca y sostienen el agarre.',
      'En casi todo ejercicio su trabajo es NO moverse: aguantan la muñeca alineada con el antebrazo.',
    ],
    porciones: [
      {
        id: 'unico',
        nombre: 'Masa flexora',
        origen: 'Epicóndilo medial del húmero',
        insercion: 'Bases de los metacarpianos, por la palma',
        desde: ['brazo', 0.96, [-0.014, 0, -0.010]],
        hasta: ['mano', 0.10, [-0.006, 0, -0.010]],
        via: [['antebrazo', 0.45, [-0.014, 0, -0.014]]],
        radio: 0.013, aplanar: 0.7, biarticular: true,
      },
    ],
  },
  {
    id: 'extensores_carpo',
    nombre: 'Extensores del carpo',
    grupo: 'codo',
    acciones: [
      'Abren la muñeca y equilibran a los flexores.',
      'Son los que evitan que la muñeca se doble hacia atrás con la barra encima.',
    ],
    porciones: [
      {
        id: 'unico',
        nombre: 'Masa extensora',
        origen: 'Epicóndilo lateral del húmero',
        insercion: 'Bases de los metacarpianos, por el dorso',
        desde: ['brazo', 0.94, [0.016, 0, 0.008]],
        hasta: ['mano', 0.10, [0.006, 0, 0.010]],
        via: [['antebrazo', 0.45, [0.016, 0, 0.012]]],
        radio: 0.012, aplanar: 0.7, biarticular: true,
      },
    ],
  },
  {
    id: 'esternocleidomastoideo',
    nombre: 'Esternocleidomastoideo',
    grupo: 'tronco',
    acciones: [
      'Flexiona el cuello y gira la cabeza hacia el lado contrario.',
      'Los dos a la vez adelantan la cabeza; es el que se marca al mirar hacia abajo.',
    ],
    porciones: [
      {
        id: 'esternal',
        nombre: 'Fascículo esternal',
        origen: 'Manubrio del esternón',
        insercion: 'Apófisis mastoides del temporal',
        desde: ['torax', 0.26, [0.014, 0, 0.082]],
        hasta: ['craneo', 0.30, [0.040, 0, -0.014]],
        radio: 0.011, aplanar: 0.7, biarticular: true,
      },
      {
        id: 'clavicular',
        nombre: 'Fascículo clavicular',
        origen: 'Tercio medial de la clavícula',
        insercion: 'Apófisis mastoides, con el fascículo esternal',
        desde: ['clavicula', 0.24, [0.004, 0, 0.010]],
        hasta: ['craneo', 0.28, [0.042, 0, -0.010]],
        radio: 0.010, aplanar: 0.7, biarticular: true,
      },
    ],
  },
  {
    id: 'escalenos',
    nombre: 'Escalenos',
    grupo: 'tronco',
    acciones: [
      'Inclinan el cuello de lado y elevan las dos primeras costillas.',
      'Cuando cuesta respirar, tiran del tórax hacia arriba.',
    ],
    porciones: [
      {
        id: 'unico',
        nombre: 'Haz común',
        origen: 'Apófisis transversas de las vértebras cervicales',
        insercion: 'Primera y segunda costillas',
        desde: ['cuello', 0.55, [0.024, 0, 0.006]],
        hasta: ['torax', 0.86, [0.046, 0, 0.030]],
        radio: 0.009, aplanar: 0.65,
      },
    ],
  },
  {
    id: 'esplenio',
    nombre: 'Esplenio y suboccipitales',
    grupo: 'tronco',
    acciones: [
      'Extienden el cuello y sostienen la cabeza contra su propio peso.',
      'Son los que aguantan cuando el tronco se inclina y la mirada se queda al frente.',
    ],
    porciones: [
      {
        id: 'esplenio',
        nombre: 'Esplenio de la cabeza',
        origen: 'Ligamento nucal y apófisis espinosas cervicales bajas',
        insercion: 'Apófisis mastoides y línea nucal del occipital',
        desde: ['torax', 0.96, [0.014, 0, -0.032]],
        hasta: ['craneo', 0.22, [0.030, 0, -0.048]],
        radio: 0.011, aplanar: 0.55, biarticular: true,
      },
      {
        id: 'suboccipitales',
        nombre: 'Suboccipitales',
        origen: 'Axis y atlas',
        insercion: 'Línea nucal inferior del occipital',
        desde: ['cuello', 0.86, [0.012, 0, -0.024]],
        hasta: ['craneo', 0.12, [0.018, 0, -0.042]],
        radio: 0.008, aplanar: 0.6,
      },
    ],
  },
]
