/**
 * Musculatura del tren inferior y del tronco, por porciones.
 *
 * Los desplazamientos son locales al hueso del visor. Ojo con los ejes: fémur,
 * tibia, húmero y antebrazo llevan un reposo de 180° en X, así que en ESOS
 * huesos el +Z local apunta hacia ATRÁS del cuerpo.
 *
 * La X del desplazamiento se multiplica por el lado, de modo que cada músculo
 * se declara una sola vez y sirve para los dos.
 */

import type { Musculo } from './anatomia'

export const MUSCULOS_INFERIOR: Musculo[] = [
  // ============================ CADERA ====================================
  {
    id: 'gluteo_mayor',
    nombre: 'Glúteo mayor',
    grupo: 'cadera',
    acciones: [
      'Extiende la cadera: es el motor de todo lo que empuja el suelo.',
      'Rota la cadera hacia fuera.',
      'Sus fibras altas también separan la pierna.',
    ],
    porciones: [
      {
        id: 'superior',
        nombre: 'Fibras superiores',
        origen: 'Cara glútea del ilion, por detrás de la línea glútea posterior',
        insercion: 'Tracto iliotibial',
        desde: ['pelvis', 0, [0.062, 0.072, -0.052]],
        hasta: ['muslo', 0.2, [0.042, 0, 0.022]],
        via: [['muslo', 0.05, [0.05, 0, 0.036]]],
        radio: 0.026, aplanar: 0.68, fasciculos: 2,
        abanicoDesde: [0.014, -0.026, 0.012],
      },
      {
        id: 'inferior',
        nombre: 'Fibras inferiores',
        origen: 'Sacro, cóccix y ligamento sacrotuberoso',
        insercion: 'Tuberosidad glútea del fémur',
        desde: ['pelvis', 0, [0.030, 0.010, -0.062]],
        hasta: ['muslo', 0.3, [0.016, 0, 0.032]],
        via: [['muslo', 0.06, [0.036, 0, 0.046]]],
        radio: 0.028, aplanar: 0.74, fasciculos: 2,
        abanicoDesde: [0.020, -0.048, 0.010],
      },
    ],
  },
  {
    id: 'gluteo_medio',
    nombre: 'Glúteo medio',
    grupo: 'cadera',
    acciones: [
      'Separa la pierna de la línea media.',
      'Sujeta la pelvis cuando apoyas sobre una sola pierna: si falla, la cadera cae.',
    ],
    porciones: [
      {
        id: 'anterior',
        nombre: 'Fibras anteriores',
        origen: 'Cara glútea del ilion, por delante de la línea glútea anterior',
        insercion: 'Cara lateral del trocánter mayor',
        desde: ['pelvis', 0, [0.080, 0.078, 0.020]],
        hasta: ['muslo', 0.06, [0.030, 0, -0.004]],
        radio: 0.020, aplanar: 0.7,
      },
      {
        id: 'posterior',
        nombre: 'Fibras posteriores',
        origen: 'Cara glútea del ilion, entre las líneas glúteas anterior y posterior',
        insercion: 'Cara lateral del trocánter mayor',
        desde: ['pelvis', 0, [0.078, 0.076, -0.034]],
        hasta: ['muslo', 0.06, [0.031, 0, 0.008]],
        radio: 0.020, aplanar: 0.7,
      },
    ],
  },
  {
    id: 'gluteo_menor',
    nombre: 'Glúteo menor',
    grupo: 'cadera',
    acciones: ['Separa la cadera y la rota hacia dentro; trabaja escondido bajo el medio.'],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre único',
        origen: 'Cara glútea del ilion, por debajo del glúteo medio',
        insercion: 'Borde anterior del trocánter mayor',
        desde: ['pelvis', 0, [0.072, 0.048, 0.002]],
        hasta: ['muslo', 0.05, [0.028, 0, -0.012]],
        radio: 0.015, aplanar: 0.72,
      },
    ],
  },
  {
    id: 'tfl',
    nombre: 'Tensor de la fascia lata',
    grupo: 'cadera',
    acciones: [
      'Separa y flexiona la cadera.',
      'Tensa el tracto iliotibial: por eso se lleva el trabajo cuando el glúteo medio no entra.',
    ],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre y tracto iliotibial',
        origen: 'Espina ilíaca anterosuperior',
        insercion: 'Tubérculo de Gerdy, en el cóndilo lateral de la tibia',
        desde: ['pelvis', 0, [0.076, 0.074, 0.030]],
        hasta: ['tibia', 0.06, [0.030, 0, -0.002]],
        via: [['muslo', 0.55, [0.046, 0, 0.002]]],
        radio: 0.012, aplanar: 0.5, biarticular: true,
      },
    ],
  },
  {
    id: 'aductores',
    nombre: 'Aductores',
    grupo: 'cadera',
    acciones: [
      'Juntan la pierna hacia la línea media.',
      'El aductor mayor también extiende la cadera: por eso trabaja en cada sentadilla profunda.',
    ],
    porciones: [
      {
        id: 'mayor',
        nombre: 'Aductor mayor',
        origen: 'Rama isquiopubiana y tuberosidad isquiática',
        insercion: 'Línea áspera y tubérculo del aductor del fémur',
        desde: ['pelvis', 0, [0.032, -0.056, 0.004]],
        hasta: ['muslo', 0.72, [0.020, 0, 0.014]],
        radio: 0.021, aplanar: 0.74, fasciculos: 2,
        abanicoDesde: [0.014, 0.010, -0.024],
        abanicoHasta: [0.002, -0.120, 0.004],
      },
      {
        id: 'largo',
        nombre: 'Aductor largo',
        origen: 'Cuerpo del pubis, bajo la cresta púbica',
        insercion: 'Tercio medio de la línea áspera',
        desde: ['pelvis', 0, [0.018, -0.048, 0.026]],
        hasta: ['muslo', 0.5, [0.020, 0, 0.008]],
        radio: 0.016, aplanar: 0.7,
      },
      {
        id: 'gracil',
        nombre: 'Grácil',
        origen: 'Rama inferior del pubis',
        insercion: 'Pata de ganso, en la cara medial de la tibia',
        desde: ['pelvis', 0, [0.014, -0.056, 0.014]],
        hasta: ['tibia', 0.10, [0.016, 0, -0.006]],
        via: [['muslo', 0.6, [0.026, 0, 0.006]]],
        radio: 0.010, aplanar: 0.8, biarticular: true,
      },
    ],
  },
  {
    id: 'psoas_iliaco',
    nombre: 'Psoas ilíaco',
    grupo: 'cadera',
    acciones: [
      'Flexiona la cadera: es el que sube la rodilla.',
      'Con la pierna fija, inclina el tronco hacia delante.',
    ],
    porciones: [
      {
        id: 'psoas',
        nombre: 'Psoas mayor',
        origen: 'Cuerpos y apófisis transversas de las vértebras lumbares',
        insercion: 'Trocánter menor del fémur',
        desde: ['lumbar', 0.7, [0.026, 0, 0.006]],
        hasta: ['muslo', 0.12, [0.020, 0, 0.006]],
        via: [['pelvis', 0, [0.034, -0.020, 0.040]]],
        radio: 0.015, aplanar: 0.85, biarticular: true,
      },
      {
        id: 'iliaco',
        nombre: 'Ilíaco',
        origen: 'Fosa ilíaca',
        insercion: 'Trocánter menor del fémur, junto al psoas',
        desde: ['pelvis', 0, [0.056, 0.040, 0.020]],
        hasta: ['muslo', 0.12, [0.022, 0, 0.010]],
        via: [['pelvis', 0, [0.036, -0.024, 0.044]]],
        radio: 0.014, aplanar: 0.7,
      },
    ],
  },

  // ============================ RODILLA ===================================
  {
    id: 'cuadriceps',
    nombre: 'Cuádriceps',
    grupo: 'rodilla',
    acciones: [
      'Extiende la rodilla: los cuatro vientres tiran del mismo tendón rotuliano.',
      'El recto femoral, además, flexiona la cadera.',
    ],
    porciones: [
      {
        id: 'recto',
        nombre: 'Recto femoral',
        origen: 'Espina ilíaca anteroinferior',
        insercion: 'Rótula y tuberosidad tibial, por el tendón rotuliano',
        desde: ['pelvis', 0, [0.052, 0.044, 0.038]],
        hasta: ['tibia', 0.07, [0, 0, -0.034]],
        via: [['muslo', 0.55, [0.004, 0, -0.042]]],
        radio: 0.019, aplanar: 0.82, biarticular: true,
      },
      {
        id: 'vasto_lateral',
        nombre: 'Vasto lateral',
        origen: 'Trocánter mayor y labio lateral de la línea áspera',
        insercion: 'Borde lateral de la rótula',
        desde: ['muslo', 0.14, [0.030, 0, 0.014]],
        hasta: ['tibia', 0.07, [0.012, 0, -0.032]],
        via: [['muslo', 0.62, [0.030, 0, -0.030]]],
        radio: 0.021, aplanar: 0.8,
      },
      {
        id: 'vasto_medial',
        nombre: 'Vasto medial',
        origen: 'Labio medial de la línea áspera',
        insercion: 'Borde medial de la rótula',
        desde: ['muslo', 0.22, [-0.020, 0, 0.014]],
        hasta: ['tibia', 0.07, [-0.014, 0, -0.032]],
        via: [['muslo', 0.70, [-0.026, 0, -0.028]]],
        radio: 0.019, aplanar: 0.8,
      },
      {
        id: 'vasto_intermedio',
        nombre: 'Vasto intermedio',
        origen: 'Caras anterior y lateral del cuerpo del fémur',
        insercion: 'Base de la rótula, bajo el recto femoral',
        desde: ['muslo', 0.24, [0.004, 0, -0.020]],
        hasta: ['tibia', 0.07, [0, 0, -0.030]],
        via: [['muslo', 0.66, [0.004, 0, -0.034]]],
        radio: 0.016, aplanar: 0.85,
      },
    ],
  },
  {
    id: 'isquiotibiales',
    nombre: 'Isquiotibiales',
    grupo: 'rodilla',
    acciones: [
      'Flexionan la rodilla y extienden la cadera.',
      'Salvo la cabeza corta del bíceps, todos cruzan dos articulaciones: por eso el estiramiento depende de dónde tengas la cadera.',
    ],
    porciones: [
      {
        id: 'biceps_larga',
        nombre: 'Bíceps femoral · cabeza larga',
        origen: 'Tuberosidad isquiática',
        insercion: 'Cabeza del peroné',
        desde: ['pelvis', 0, [0.058, -0.064, -0.020]],
        hasta: ['tibia', 0.08, [0.026, 0, 0.024]],
        via: [['muslo', 0.55, [0.026, 0, 0.040]]],
        radio: 0.018, aplanar: 0.82, biarticular: true,
      },
      {
        id: 'biceps_corta',
        nombre: 'Bíceps femoral · cabeza corta',
        origen: 'Labio lateral de la línea áspera del fémur',
        insercion: 'Cabeza del peroné, con la cabeza larga',
        desde: ['muslo', 0.5, [0.024, 0, 0.030]],
        hasta: ['tibia', 0.08, [0.026, 0, 0.022]],
        radio: 0.013, aplanar: 0.82,
      },
      {
        id: 'semitendinoso',
        nombre: 'Semitendinoso',
        origen: 'Tuberosidad isquiática',
        insercion: 'Pata de ganso, en la cara medial de la tibia',
        desde: ['pelvis', 0, [0.046, -0.066, -0.018]],
        hasta: ['tibia', 0.10, [-0.018, 0, 0.014]],
        via: [['muslo', 0.58, [-0.010, 0, 0.042]]],
        radio: 0.014, aplanar: 0.85, biarticular: true,
      },
      {
        id: 'semimembranoso',
        nombre: 'Semimembranoso',
        origen: 'Tuberosidad isquiática, por delante del semitendinoso',
        insercion: 'Cóndilo medial de la tibia',
        desde: ['pelvis', 0, [0.052, -0.062, -0.010]],
        hasta: ['tibia', 0.06, [-0.020, 0, 0.022]],
        via: [['muslo', 0.60, [-0.020, 0, 0.038]]],
        radio: 0.016, aplanar: 0.8, biarticular: true,
      },
    ],
  },
  {
    id: 'poplíteo',
    nombre: 'Poplíteo',
    grupo: 'rodilla',
    acciones: ['Desbloquea la rodilla al empezar a doblarla, rotando la tibia hacia dentro.'],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre único',
        origen: 'Cóndilo lateral del fémur',
        insercion: 'Cara posterior de la tibia, sobre la línea del sóleo',
        desde: ['muslo', 0.95, [0.020, 0, 0.026]],
        hasta: ['tibia', 0.16, [-0.014, 0, 0.024]],
        radio: 0.010, aplanar: 0.7,
      },
    ],
  },

  // ============================ TOBILLO ===================================
  {
    id: 'triceps_sural',
    nombre: 'Tríceps sural',
    grupo: 'tobillo',
    acciones: [
      'Empuja el suelo con la punta del pie: es la flexión plantar.',
      'Los gemelos cruzan la rodilla y el sóleo no: por eso sentado trabajas sobre todo el sóleo.',
    ],
    porciones: [
      {
        id: 'gastro_medial',
        nombre: 'Gastrocnemio medial',
        origen: 'Cóndilo medial del fémur',
        insercion: 'Calcáneo, por el tendón de Aquiles',
        desde: ['muslo', 0.96, [-0.020, 0, 0.030]],
        hasta: ['pie', 0, [-0.004, -0.022, -0.034]],
        via: [['tibia', 0.40, [-0.016, 0, 0.040]], ['tibia', 0.86, [-0.006, 0, 0.026]]],
        radio: 0.019, aplanar: 0.85, biarticular: true,
      },
      {
        id: 'gastro_lateral',
        nombre: 'Gastrocnemio lateral',
        origen: 'Cóndilo lateral del fémur',
        insercion: 'Calcáneo, por el tendón de Aquiles',
        desde: ['muslo', 0.96, [0.022, 0, 0.030]],
        hasta: ['pie', 0, [0.004, -0.022, -0.034]],
        via: [['tibia', 0.40, [0.018, 0, 0.038]], ['tibia', 0.86, [0.006, 0, 0.026]]],
        radio: 0.017, aplanar: 0.85, biarticular: true,
      },
      {
        id: 'soleo',
        nombre: 'Sóleo',
        origen: 'Línea del sóleo de la tibia y cabeza del peroné',
        insercion: 'Calcáneo, por el tendón de Aquiles',
        desde: ['tibia', 0.22, [0.006, 0, 0.032]],
        hasta: ['pie', 0, [0, -0.020, -0.032]],
        via: [['tibia', 0.62, [0.006, 0, 0.036]]],
        radio: 0.019, aplanar: 0.88,
      },
    ],
  },
  {
    id: 'tibial_anterior',
    nombre: 'Tibial anterior',
    grupo: 'tobillo',
    acciones: [
      'Levanta la punta del pie.',
      'Es lo que te falta cuando el talón se despega en sentadilla.',
    ],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre único',
        origen: 'Cóndilo lateral y cara lateral de la tibia',
        insercion: 'Primer cuneiforme y base del primer metatarsiano',
        desde: ['tibia', 0.24, [0.020, 0, -0.022]],
        hasta: ['pie', 0.36, [0.010, 0, -0.008]],
        radio: 0.013, aplanar: 0.7,
      },
    ],
  },
  {
    id: 'peroneos',
    nombre: 'Peroneos',
    grupo: 'tobillo',
    acciones: ['Llevan el pie hacia fuera y sostienen el tobillo al apoyar.'],
    porciones: [
      {
        id: 'largo',
        nombre: 'Peroneo largo',
        origen: 'Cabeza y dos tercios superiores del peroné',
        insercion: 'Base del primer metatarsiano, por la planta',
        desde: ['tibia', 0.20, [0.028, 0, 0.004]],
        hasta: ['pie', 0.30, [0.016, 0, 0.006]],
        via: [['tibia', 0.88, [0.026, 0, 0.010]]],
        radio: 0.010, aplanar: 0.75,
      },
    ],
  },

  // ============================= TRONCO ===================================
  {
    id: 'erectores',
    nombre: 'Erectores espinales',
    grupo: 'tronco',
    acciones: [
      'Sostienen la columna: en un peso muerto su trabajo es que la espalda NO se doble.',
      'Extienden el tronco cuando te incorporas.',
    ],
    porciones: [
      {
        id: 'iliocostal',
        nombre: 'Iliocostal',
        origen: 'Cresta ilíaca y sacro',
        insercion: 'Ángulos de las costillas',
        desde: ['pelvis', 0, [0.038, 0.020, -0.046]],
        hasta: ['torax', 0.80, [0.036, 0, -0.034]],
        via: [['lumbar', 0.5, [0.038, 0, -0.036]]],
        radio: 0.014, aplanar: 0.72,
      },
      {
        id: 'longisimo',
        nombre: 'Longísimo',
        origen: 'Sacro y apófisis transversas lumbares',
        insercion: 'Apófisis transversas torácicas y costillas',
        desde: ['pelvis', 0, [0.024, 0.020, -0.050]],
        hasta: ['torax', 0.90, [0.020, 0, -0.036]],
        via: [['lumbar', 0.5, [0.026, 0, -0.040]], ['torax', 0.45, [0.024, 0, -0.040]]],
        radio: 0.015, aplanar: 0.75,
      },
      {
        id: 'espinal',
        nombre: 'Espinal',
        origen: 'Apófisis espinosas lumbares altas',
        insercion: 'Apófisis espinosas torácicas',
        desde: ['lumbar', 0.15, [0.010, 0, -0.042]],
        hasta: ['torax', 0.70, [0.010, 0, -0.038]],
        radio: 0.010, aplanar: 0.7,
      },
    ],
  },
  {
    id: 'recto_abdominal',
    nombre: 'Recto abdominal',
    grupo: 'tronco',
    acciones: [
      'Acerca las costillas a la pelvis.',
      'En una plancha no acorta nada: aguanta para que la espalda no se arquee.',
    ],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre con sus intersecciones',
        origen: 'Cresta del pubis y sínfisis púbica',
        insercion: 'Cartílagos costales 5.º a 7.º y apéndice xifoides',
        desde: ['pelvis', 0, [0.020, -0.032, 0.046]],
        hasta: ['torax', 0.24, [0.022, 0, 0.101]],
        via: [['lumbar', 0.55, [0.021, 0, 0.078]]],
        radio: 0.017, aplanar: 0.6,
      },
    ],
  },
  {
    id: 'oblicuos',
    nombre: 'Oblicuos',
    grupo: 'tronco',
    acciones: [
      'Giran e inclinan el tronco.',
      'Impiden que gire cuando no debe: eso es lo que sujetan en un press a una mano.',
    ],
    porciones: [
      {
        id: 'externo',
        nombre: 'Oblicuo externo',
        origen: 'Caras externas de las costillas 5.ª a 12.ª',
        insercion: 'Cresta ilíaca y línea alba',
        desde: ['torax', 0.44, [0.052, 0, 0.046]],
        hasta: ['pelvis', 0, [0.070, 0.036, 0.014]],
        radio: 0.017, aplanar: 0.5, fasciculos: 2,
        abanicoDesde: [0.008, 0.060, -0.052],
      },
      {
        id: 'interno',
        nombre: 'Oblicuo interno',
        origen: 'Cresta ilíaca, ligamento inguinal y fascia toracolumbar',
        insercion: 'Costillas 10.ª a 12.ª y línea alba',
        desde: ['pelvis', 0, [0.066, 0.040, -0.010]],
        hasta: ['torax', 0.30, [0.056, 0, 0.038]],
        radio: 0.014, aplanar: 0.5,
      },
    ],
  },
  {
    id: 'transverso',
    nombre: 'Transverso del abdomen',
    grupo: 'tronco',
    acciones: ['Ciñe el abdomen como un cinturón; es el más profundo de la pared.'],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre único',
        origen: 'Cresta ilíaca, fascia toracolumbar y cartílagos costales bajos',
        insercion: 'Línea alba',
        desde: ['pelvis', 0, [0.062, 0.036, -0.022]],
        hasta: ['lumbar', 0.5, [0.008, 0, 0.066]],
        via: [['lumbar', 0.3, [0.062, 0, 0.030]]],
        radio: 0.011, aplanar: 0.45,
      },
    ],
  },
  {
    id: 'cuadrado_lumbar',
    nombre: 'Cuadrado lumbar',
    grupo: 'tronco',
    acciones: [
      'Inclina el tronco de lado y sujeta la pelvis.',
      'Es el que aguanta cuando cargas peso en una sola mano.',
    ],
    porciones: [
      {
        id: 'unico',
        nombre: 'Vientre único',
        origen: 'Cresta ilíaca y ligamento iliolumbar',
        insercion: '12.ª costilla y apófisis transversas lumbares',
        desde: ['pelvis', 0, [0.048, 0.048, -0.030]],
        hasta: ['lumbar', 0.95, [0.030, 0, -0.020]],
        radio: 0.013, aplanar: 0.6,
      },
    ],
  },
]
